/**
 * seed/notices.js
 * Canonical Notice System Seed Data
 *
 * This is the SINGLE canonical notice system for ALL portals.
 * No separate studentNotices, teacherNotices, parentNotices.
 * Audience targeting handles role-based delivery.
 */

// === NOTICE CATEGORIES ===
export const NOTICE_CATEGORIES = {
  ACADEMIC: "academic",
  EXAMINATION: "examination",
  ATTENDANCE: "attendance",
  FEES: "fees",
  TRANSPORT: "transport",
  DISCIPLINE: "discipline",
  HOLIDAY: "holiday",
  EVENT: "event",
  ADMINISTRATIVE: "administrative",
  EMERGENCY: "emergency",
  RESULTS: "results",
  TIMETABLE: "timetable",
  PTM: "ptm",
  SYSTEM: "system",
};

// === NOTICE PRIORITIES ===
export const NOTICE_PRIORITIES = {
  INFO: "info",
  IMPORTANT: "important",
  URGENT: "urgent",
  CRITICAL: "critical",
};

// === NOTICE LIFECYCLE STATES ===
export const NOTICE_STATUS = {
  DRAFT: "draft",
  SCHEDULED: "scheduled",
  PUBLISHED: "published",
  ARCHIVED: "archived",
  EXPIRED: "expired",
  CANCELLED: "cancelled",
};

// === AUDIENCE TYPES ===
export const AUDIENCE_TYPES = {
  ALL: "ALL",
  STUDENTS: "STUDENTS",
  TEACHERS: "TEACHERS",
  PARENTS: "PARENTS",
  CLASS: "CLASS",
  STREAM: "STREAM",
  SPECIFIC: "SPECIFIC",
};

// === DELIVERY CHANNELS ===
export const DELIVERY_CHANNELS = {
  PORTAL: "portal",
  EMAIL: "email",
  SMS: "sms",
  PUSH: "push",
  WHATSAPP: "whatsapp",
};

// === ACTION TYPES ===
export const ACTION_TYPES = {
  NONE: "none",
  ACKNOWLEDGE: "acknowledge",
  RSVP: "rsvp",
  PAYMENT: "payment",
  FORM_SUBMISSION: "form_submission",
  DOCUMENT_UPLOAD: "document_upload",
};

/**
 * Canonical Notice Schema
 * {
 *   id: string,
 *   title: string,
 *   message: string,
 *   category: NOTICE_CATEGORIES,
 *   priority: NOTICE_PRIORITIES,
 *   sourceModule: string,
 *   status: NOTICE_STATUS,
 *   targetAudience: {
 *     type: AUDIENCE_TYPES,
 *     classIds?: string[],
 *     streamIds?: string[],
 *     studentIds?: string[],
 *     teacherIds?: string[],
 *     parentIds?: string[],
 *   },
 *   deliveryChannels: DELIVERY_CHANNELS[],
 *   requiresAction: boolean,
 *   actionType: ACTION_TYPES,
 *   metadata: object,
 *   createdBy: string,
 *   createdAt: string (ISO),
 *   publishedAt: string (ISO) | null, // For scheduled notices, this is the scheduled publish time
 *   expiresAt: string (ISO) | null, // Auto-expiry time
 *   autoArchiveAfter: number | null, // Days after expiry to auto-archive (optional)
 *   readReceipts: {
 *     userId: string,
 *     readAt: string (ISO),
 *   }[],
 *   actionResponses: {
 *     userId: string,
 *     responseType: "acknowledged" | "accepted" | "declined" | "submitted",
 *     responseAt: string (ISO),
 *     responseData?: object, // For form submissions, RSVP details, etc.
 *   }[],
 *   actionDeadline: string (ISO) | null, // Deadline for action completion
 * }
 */

export const noticeSeedData = [
  {
    id: "notice-001",
    title: "Half-Yearly Examination Schedule Released",
    message:
      "The half-yearly examination schedule for the academic session 2025-26 has been released. Exams will commence from 15th July 2025. Students are advised to check the detailed timetable and prepare accordingly.",
    category: NOTICE_CATEGORIES.EXAMINATION,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.STUDENTS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      examSessionId: "exam-session-2025-hy",
      attachmentUrl: "/documents/exam-schedule-2025.pdf",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-10T08:00:00Z",
    publishedAt: "2025-07-10T08:00:00Z",
    expiresAt: "2025-08-01T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-002",
    title: "School Library Closed for Maintenance",
    message:
      "The school library will remain closed on 15th July 2025 for annual maintenance and book inventory. Students and staff are requested to plan accordingly. Normal operations will resume from 16th July 2025.",
    category: NOTICE_CATEGORIES.ADMINISTRATIVE,
    priority: NOTICE_PRIORITIES.INFO,
    sourceModule: "administration",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.ALL,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {},
    createdBy: "admin-001",
    createdAt: "2025-07-08T10:00:00Z",
    publishedAt: "2025-07-08T10:00:00Z",
    expiresAt: "2025-07-16T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-003",
    title: "Annual Sports Day Registration Open",
    message:
      "Registration for Annual Sports Day 2025 is now open. Students interested in participating in track events, team sports, and cultural performances must register by 20th July 2025. Contact the sports department for event details.",
    category: NOTICE_CATEGORIES.EVENT,
    priority: NOTICE_PRIORITIES.INFO,
    sourceModule: "events",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.STUDENTS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.PUSH],
    requiresAction: true,
    actionType: ACTION_TYPES.FORM_SUBMISSION,
    metadata: {
      eventId: "sports-day-2025",
      registrationDeadline: "2025-07-20T23:59:59Z",
      eventDate: "2025-08-15T09:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-05T14:00:00Z",
    publishedAt: "2025-07-05T14:00:00Z",
    expiresAt: "2025-07-21T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-004",
    title: "Parent-Teacher Meeting Scheduled",
    message:
      "Parent-Teacher Meeting for all classes is scheduled on 20th July 2025 from 9:00 AM to 12:00 PM. Parents are requested to attend the meeting to discuss their ward's academic progress. Individual appointments can be scheduled with class teachers.",
    category: NOTICE_CATEGORIES.PTM,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "academics",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.PARENTS,
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.EMAIL,
      DELIVERY_CHANNELS.SMS,
    ],
    requiresAction: true,
    actionType: ACTION_TYPES.RSVP,
    metadata: {
      ptmDate: "2025-07-20T09:00:00Z",
      venue: "School Auditorium",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-09T11:00:00Z",
    publishedAt: "2025-07-09T11:00:00Z",
    expiresAt: "2025-07-21T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-005",
    title: "Fee Payment Reminder - Q2 2025-26",
    message:
      "This is a reminder that the second quarter fee payment for the academic session 2025-26 is due by 31st July 2025. Late payment will attract a penalty of 5% per month. Please ensure timely payment to avoid inconvenience.",
    category: NOTICE_CATEGORIES.FEES,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "finance",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.PARENTS,
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.EMAIL,
      DELIVERY_CHANNELS.SMS,
    ],
    requiresAction: true,
    actionType: ACTION_TYPES.PAYMENT,
    metadata: {
      quarter: "Q2",
      dueDate: "2025-07-31T23:59:59Z",
      lateFeePercentage: 5,
    },
    createdBy: "admin-001",
    createdAt: "2025-07-12T09:00:00Z",
    publishedAt: "2025-07-12T09:00:00Z",
    expiresAt: "2025-08-01T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-006",
    title: "Submit Mid-Term Marks - Class XI Science",
    message:
      "Mid-term examination marks for Class XI Science subjects (Physics, Chemistry, Mathematics, Biology, Computer Science) must be submitted by 20th July 2025. Please ensure all marks are entered in the examination module before the deadline.",
    category: NOTICE_CATEGORIES.EXAMINATION,
    priority: NOTICE_PRIORITIES.URGENT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.TEACHERS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: true,
    actionType: ACTION_TYPES.FORM_SUBMISSION,
    metadata: {
      examSession: "mid-term",
      targetClasses: ["class-11a", "class-11b", "class-11c", "class-11d"],
      deadline: "2025-07-20T23:59:59Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T10:00:00Z",
    publishedAt: "2025-07-14T10:00:00Z",
    expiresAt: "2025-07-21T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-007",
    title: "Leave Request Approval Pending - 3 Requests",
    message:
      "You have 3 student leave requests pending approval in your dashboard. Please review and approve or reject these requests by end of day today. Students: Rahul Sharma (Class 10-A), Priya Singh (Class 10-B), Amit Kumar (Class 9-A).",
    category: NOTICE_CATEGORIES.ATTENDANCE,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "attendance",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.SPECIFIC,
      teacherIds: ["teach-001", "teach-002", "teach-003"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      pendingCount: 3,
      studentIds: ["stu-001", "stu-002", "stu-003"],
      deadline: "2025-07-14T18:00:00Z",
    },
    createdBy: "system",
    createdAt: "2025-07-14T08:00:00Z",
    publishedAt: "2025-07-14T08:00:00Z",
    expiresAt: "2025-07-15T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-008",
    title: "PTM Scheduled - 25th July 2025",
    message:
      "Parent-Teacher Meeting for Class 6-10 is scheduled on 25th July 2025 from 9:00 AM to 1:00 PM. All subject teachers are required to attend. Please prepare student performance reports and discussion points. Room assignments will be shared by 22nd July.",
    category: NOTICE_CATEGORIES.PTM,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "administrative",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.TEACHERS,
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.EMAIL,
      DELIVERY_CHANNELS.SMS,
    ],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      ptmDate: "2025-07-25T09:00:00Z",
      ptmEndTime: "2025-07-25T13:00:00Z",
      targetClasses: [
        "class-6a",
        "class-6b",
        "class-7a",
        "class-7b",
        "class-8a",
        "class-8b",
        "class-9a",
        "class-9b",
        "class-10a",
        "class-10b",
      ],
    },
    createdBy: "admin-001",
    createdAt: "2025-07-13T14:00:00Z",
    publishedAt: "2025-07-13T14:00:00Z",
    expiresAt: "2025-07-26T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-009",
    title: "Daily Attendance Not Published - 3 Days",
    message:
      "Daily attendance for the last 3 days (11th, 12th, 13th July) has not been published for your assigned classes. Please update and publish attendance records immediately. This is required for student attendance percentage calculation.",
    category: NOTICE_CATEGORIES.ATTENDANCE,
    priority: NOTICE_PRIORITIES.URGENT,
    sourceModule: "attendance",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.SPECIFIC,
      teacherIds: ["teach-004", "teach-005"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      missingDates: ["2025-07-11", "2025-07-12", "2025-07-13"],
      classIds: ["class-6a", "class-6b"],
    },
    createdBy: "system",
    createdAt: "2025-07-14T07:00:00Z",
    publishedAt: "2025-07-14T07:00:00Z",
    expiresAt: "2025-07-15T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-010",
    title: "Invigilation Duty - Final Exams",
    message:
      "Invigilation duty roster for final examinations (July-August 2025) has been published. Please check your assigned dates and venues. Report to the examination center 30 minutes before the scheduled start time. Any swap requests must be submitted 48 hours in advance.",
    category: NOTICE_CATEGORIES.EXAMINATION,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.TEACHERS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      examPeriod: "final",
      startDate: "2025-07-20T00:00:00Z",
      endDate: "2025-08-10T00:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-10T11:00:00Z",
    publishedAt: "2025-07-10T11:00:00Z",
    expiresAt: "2025-08-15T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-011",
    title: "Syllabus Completion Deadline - Term 1",
    message:
      "Term 1 syllabus completion deadline is 15th August 2025. Please ensure all topics are covered and revision begins by 20th July. Submit your completion status report by 10th August for academic review.",
    category: NOTICE_CATEGORIES.ACADEMIC,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "academic",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.TEACHERS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      term: "Term 1",
      completionDeadline: "2025-08-15T00:00:00Z",
      reportDeadline: "2025-08-10T00:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-08T09:00:00Z",
    publishedAt: "2025-07-08T09:00:00Z",
    expiresAt: "2025-08-20T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-012",
    title: "Staff Meeting - Academic Planning",
    message:
      "Mandatory staff meeting for academic planning for the upcoming academic session 2026-27. Date: 18th July 2025, Time: 2:30 PM, Venue: Conference Room. Agenda: Curriculum review, new subject introduction, resource allocation.",
    category: NOTICE_CATEGORIES.ADMINISTRATIVE,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "administrative",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.TEACHERS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      meetingDate: "2025-07-18T14:30:00Z",
      venue: "Conference Room",
      agenda: [
        "Curriculum review",
        "New subject introduction",
        "Resource allocation",
      ],
    },
    createdBy: "admin-001",
    createdAt: "2025-07-12T10:00:00Z",
    publishedAt: "2025-07-12T10:00:00Z",
    expiresAt: "2025-07-19T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-013",
    title: "Parent Escalation - Student Discipline Issue",
    message:
      "Parent of student Arjun Verma (Class 8-A, Roll 15) has escalated a discipline concern. The parent alleges bullying incidents during recess. Please investigate and provide a report by 16th July 2025. Meeting with parents scheduled for 17th July at 11:00 AM.",
    category: NOTICE_CATEGORIES.DISCIPLINE,
    priority: NOTICE_PRIORITIES.URGENT,
    sourceModule: "discipline",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-8a"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      studentId: "stu-045",
      studentName: "Arjun Verma",
      classId: "class-8a",
      reportDeadline: "2025-07-16T00:00:00Z",
      parentMeeting: "2025-07-17T11:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-13T16:00:00Z",
    publishedAt: "2025-07-13T16:00:00Z",
    expiresAt: "2025-07-18T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-014",
    title: "Holiday Declaration - Independence Day",
    message:
      "School will remain closed on 15th August 2025 (Thursday) on account of Independence Day. Regular classes will resume from 16th August 2025. Please ensure all academic activities are planned accordingly.",
    category: NOTICE_CATEGORIES.HOLIDAY,
    priority: NOTICE_PRIORITIES.INFO,
    sourceModule: "administrative",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.ALL,
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.EMAIL,
      DELIVERY_CHANNELS.SMS,
    ],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      holidayName: "Independence Day",
      date: "2025-08-15T00:00:00Z",
      resumeDate: "2025-08-16T00:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-10T09:00:00Z",
    publishedAt: "2025-07-10T09:00:00Z",
    expiresAt: "2025-08-20T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-015",
    title: "Timetable Update - New Subject Allocation",
    message:
      "Timetable has been updated effective from 20th July 2025. Computer Science has been added to Class 9 curriculum. Please check your updated schedule in the timetable module. New period allocations: P4 (Mon/Wed/Fri) for Class 9-A/B.",
    category: NOTICE_CATEGORIES.TIMETABLE,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "timetable",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.TEACHERS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      effectiveDate: "2025-07-20T00:00:00Z",
      newSubject: "Computer Science",
      targetClasses: ["class-9a", "class-9b"],
      periodAllocation: "P4 (Mon/Wed/Fri)",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T12:00:00Z",
    publishedAt: "2025-07-14T12:00:00Z",
    expiresAt: "2025-07-25T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-016",
    title: "Mid-Term Examination Schedule - Class 8",
    message:
      "Mid-term examinations for Class 8 will begin from 25th July 2025. Subjects: Mathematics (25th), Science (26th), English (27th), Social Studies (28th). Please ensure you have prepared thoroughly. Bring your admit card and stationery.",
    category: NOTICE_CATEGORIES.EXAMINATION,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-8a", "class-8b"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.SMS],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      examSession: "mid-term",
      targetClasses: ["class-8a", "class-8b"],
      startDate: "2025-07-25T00:00:00Z",
      endDate: "2025-07-28T00:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T15:00:00Z",
    publishedAt: "2025-07-14T15:00:00Z",
    expiresAt: "2025-07-30T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-017",
    title: "Mathematics Assignment Due - Class 9",
    message:
      "Chapter 5: Trigonometry assignment is due on 18th July 2025. Submit your completed work to your Mathematics teacher before 3:00 PM. Late submissions will attract a 10% penalty.",
    category: NOTICE_CATEGORIES.ACADEMIC,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "academic",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-9a", "class-9b"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL],
    requiresAction: true,
    actionType: ACTION_TYPES.FORM_SUBMISSION,
    metadata: {
      subject: "Mathematics",
      chapter: "Chapter 5: Trigonometry",
      dueDate: "2025-07-18T15:00:00Z",
      targetClasses: ["class-9a", "class-9b"],
    },
    createdBy: "admin-001",
    createdAt: "2025-07-13T10:00:00Z",
    publishedAt: "2025-07-13T10:00:00Z",
    expiresAt: "2025-07-19T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-018",
    title: "Science Project Submission - Class 10",
    message:
      "Science Fair project submissions are due on 22nd July 2025. Topic: Renewable Energy Sources. Work in groups of 4-5 students. Submit your project report and working model to the Science department.",
    category: NOTICE_CATEGORIES.ACADEMIC,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "academic",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-10a", "class-10b"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: true,
    actionType: ACTION_TYPES.FORM_SUBMISSION,
    metadata: {
      subject: "Science",
      topic: "Renewable Energy Sources",
      dueDate: "2025-07-22T00:00:00Z",
      targetClasses: ["class-10a", "class-10b"],
      groupSize: "4-5 students",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-12T14:00:00Z",
    publishedAt: "2025-07-12T14:00:00Z",
    expiresAt: "2025-07-23T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-019",
    title: "Low Attendance Warning - Class 11-A",
    message:
      "Your attendance for the current academic session is below 75%. This may affect your eligibility for examinations. Please ensure regular attendance from now onwards. Contact your class teacher for guidance.",
    category: NOTICE_CATEGORIES.ATTENDANCE,
    priority: NOTICE_PRIORITIES.URGENT,
    sourceModule: "attendance",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.SPECIFIC,
      studentIds: ["stu-045", "stu-046", "stu-047"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.SMS],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      attendancePercentage: 72,
      requiredPercentage: 75,
      classId: "class-11a",
    },
    createdBy: "system",
    createdAt: "2025-07-14T09:00:00Z",
    publishedAt: "2025-07-14T09:00:00Z",
    expiresAt: "2025-08-01T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-020",
    title: "Physics Practical Exam - Class XI",
    message:
      "Physics practical examination for Class XI students is scheduled on 18th July 2025 in Lab 1. Students must bring their practical files and observation records. Reporting time is 8:30 AM.",
    category: NOTICE_CATEGORIES.EXAMINATION,
    priority: NOTICE_PRIORITIES.URGENT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-11a", "class-11b", "class-11c", "class-11d"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.SMS],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      subject: "Physics",
      examType: "practical",
      date: "2025-07-18T08:30:00Z",
      venue: "Lab 1",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-10T10:00:00Z",
    publishedAt: "2025-07-10T10:00:00Z",
    expiresAt: "2025-07-19T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-031",
    title: "Chemistry Theory Exam - Class XI",
    message:
      "Chemistry theory examination for Class XI students is scheduled on 22nd July 2025 in Hall A. Students must carry their admit cards and stationery. Exam duration is 3 hours.",
    category: NOTICE_CATEGORIES.EXAMINATION,
    priority: NOTICE_PRIORITIES.URGENT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-11a", "class-11b", "class-11c", "class-11d"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.SMS],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      subject: "Chemistry",
      examType: "theory",
      date: "2025-07-22T09:00:00Z",
      venue: "Hall A",
      duration: "3 hours",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-10T10:30:00Z",
    publishedAt: "2025-07-10T10:30:00Z",
    expiresAt: "2025-07-23T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-021",
    title: "Fee Payment Reminder - Q3 2025-26",
    message:
      "Third quarter fee payment for the academic session 2025-26 is due by 31st October 2025. Outstanding amount: ₹25,000. Please ensure timely payment to avoid late fee charges of 5% per month.",
    category: NOTICE_CATEGORIES.FEES,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "finance",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.PARENTS,
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.EMAIL,
      DELIVERY_CHANNELS.SMS,
    ],
    requiresAction: true,
    actionType: ACTION_TYPES.PAYMENT,
    metadata: {
      quarter: "Q3",
      dueDate: "2025-10-31T23:59:59Z",
      outstandingAmount: 25000,
      lateFeePercentage: 5,
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T11:00:00Z",
    publishedAt: "2025-07-14T11:00:00Z",
    expiresAt: "2025-11-01T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-022",
    title: "Parent-Teacher Meeting - Class 6-10",
    message:
      "Parent-Teacher Meeting for Classes 6-10 is scheduled on 25th July 2025 from 9:00 AM to 1:00 PM. Please attend to discuss your child's academic progress. Individual appointment slots will be allocated on first-come-first-served basis.",
    category: NOTICE_CATEGORIES.PTM,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "administrative",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: [
        "class-6a",
        "class-6b",
        "class-7a",
        "class-7b",
        "class-8a",
        "class-8b",
        "class-9a",
        "class-9b",
        "class-10a",
        "class-10b",
      ],
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.EMAIL,
      DELIVERY_CHANNELS.SMS,
    ],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      ptmDate: "2025-07-25T09:00:00Z",
      ptmEndTime: "2025-07-25T13:00:00Z",
      targetClasses: [
        "class-6a",
        "class-6b",
        "class-7a",
        "class-7b",
        "class-8a",
        "class-8b",
        "class-9a",
        "class-9b",
        "class-10a",
        "class-10b",
      ],
    },
    createdBy: "admin-001",
    createdAt: "2025-07-13T14:00:00Z",
    publishedAt: "2025-07-13T14:00:00Z",
    expiresAt: "2025-07-26T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-023",
    title: "Bus Route Change - Route 3",
    message:
      "Effective from 20th July 2025, Bus Route 3 will have a modified schedule. New pickup time for stop: Sector 15 - 7:15 AM (was 7:30 AM). Drop-off time will remain unchanged. Please ensure your child reaches the stop on time.",
    category: NOTICE_CATEGORIES.TRANSPORT,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "transport",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.SPECIFIC,
      parentIds: ["parent-001", "parent-002", "parent-003", "parent-004"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.SMS],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      routeNumber: "Route 3",
      effectiveDate: "2025-07-20T00:00:00Z",
      stop: "Sector 15",
      newPickupTime: "7:15 AM",
      oldPickupTime: "7:30 AM",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T13:00:00Z",
    publishedAt: "2025-07-14T13:00:00Z",
    expiresAt: "2025-07-25T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-024",
    title: "Student Absence Alert - Class 8-A",
    message:
      "Your child was absent from school on 12th July 2025 without prior intimation. Please ensure you submit a leave application or provide a valid reason for the absence. Repeated unexcused absences may affect attendance percentage.",
    category: NOTICE_CATEGORIES.ATTENDANCE,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "attendance",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.SPECIFIC,
      parentIds: ["parent-015", "parent-016"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.SMS],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      absenceDate: "2025-07-12T00:00:00Z",
      studentId: "stu-045",
      classId: "class-8a",
    },
    createdBy: "system",
    createdAt: "2025-07-13T09:00:00Z",
    publishedAt: "2025-07-13T09:00:00Z",
    expiresAt: "2025-07-20T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-025",
    title: "Annual Sports Day - 15th August 2025",
    message:
      "Annual Sports Day will be celebrated on 15th August 2025 at the school ground. All parents are cordially invited to attend. Events begin at 8:00 AM. Students must come in sports uniform. Light refreshments will be provided.",
    category: NOTICE_CATEGORIES.EVENT,
    priority: NOTICE_PRIORITIES.INFO,
    sourceModule: "administrative",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.PARENTS,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      eventName: "Annual Sports Day",
      date: "2025-08-15T08:00:00Z",
      venue: "School Ground",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-10T12:00:00Z",
    publishedAt: "2025-07-10T12:00:00Z",
    expiresAt: "2025-08-20T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-040",
    title: "Mid-Term Results Published - Class 9",
    message:
      "Mid-term examination results for Class 9 have been published. Please check the student portal for detailed marks. Parent-teacher meetings to discuss performance will be scheduled next week. Contact the class teacher for any concerns.",
    category: NOTICE_CATEGORIES.RESULTS,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-9a", "class-9b"],
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.EMAIL,
      DELIVERY_CHANNELS.SMS,
    ],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      examSession: "mid-term",
      targetClasses: ["class-9a", "class-9b"],
      publishedDate: "2025-07-14T00:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T10:00:00Z",
    publishedAt: "2025-07-14T10:00:00Z",
    expiresAt: "2025-07-28T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-041",
    title: "Library Book Return Reminder",
    message:
      "Your child has borrowed library books that are due for return. Book: 'Introduction to Physics' (Due: 18th July 2025). Please ensure the book is returned on time to avoid late fees. Lost books will be charged at replacement cost.",
    category: NOTICE_CATEGORIES.ADMINISTRATIVE,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "administrative",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.SPECIFIC,
      parentIds: ["parent-020", "parent-021"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.SMS],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      bookTitle: "Introduction to Physics",
      dueDate: "2025-07-18T00:00:00Z",
      studentId: "stu-050",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T08:00:00Z",
    publishedAt: "2025-07-14T08:00:00Z",
    expiresAt: "2025-07-19T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-032",
    title: "Chemistry Theory Exam - Class XI",
    publishedAt: "2025-07-10T10:30:00Z",
    expiresAt: "2025-07-23T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-033",
    title: "Mathematics Unit Test - Class XI",
    message:
      "Mathematics unit test for Class XI students is scheduled on 25th July 2025 in Room 11A. Topics covered: Calculus and Coordinate Geometry. Test duration: 1.5 hours.",
    category: NOTICE_CATEGORIES.EXAMINATION,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-11a", "class-11b", "class-11c", "class-11d"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      subject: "Mathematics",
      examType: "unit_test",
      date: "2025-07-25T10:00:00Z",
      venue: "Room 11A",
      duration: "1.5 hours",
      topics: ["Calculus", "Coordinate Geometry"],
    },
    createdBy: "admin-001",
    createdAt: "2025-07-11T14:00:00Z",
    publishedAt: "2025-07-11T14:00:00Z",
    expiresAt: "2025-07-26T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-034",
    title: "Transport Route Change - Route 5",
    message:
      "Due to road construction on NH-48, Route 5 will be temporarily diverted via Inner Ring Road. This change is effective from 15th July 2025 until further notice. Students using Route 5 may experience a 10-15 minute delay in pickup/drop timing.",
    category: NOTICE_CATEGORIES.TRANSPORT,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "transport",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.SPECIFIC,
      studentIds: [], // Will be populated with students on Route 5
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.SMS,
      DELIVERY_CHANNELS.WHATSAPP,
    ],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      routeId: "route-5",
      effectiveFrom: "2025-07-15T00:00:00Z",
      reason: "Road construction on NH-48",
      expectedDelay: "10-15 minutes",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-13T16:00:00Z",
    publishedAt: "2025-07-13T16:00:00Z",
    expiresAt: null, // Until further notice
    readReceipts: [],
  },
  {
    id: "notice-035",
    title: "Holiday Declaration - Independence Day",
    message:
      "The school will remain closed on 15th August 2025 on account of Independence Day. Regular classes will resume from 16th August 2025. Staff and students are requested to attend the flag hoisting ceremony at 8:00 AM in the school ground.",
    category: NOTICE_CATEGORIES.HOLIDAY,
    priority: NOTICE_PRIORITIES.INFO,
    sourceModule: "administration",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.ALL,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      holidayName: "Independence Day",
      date: "2025-08-15T00:00:00Z",
      ceremonyTime: "2025-08-15T08:00:00Z",
      venue: "School Ground",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-14T09:00:00Z",
    publishedAt: "2025-07-14T09:00:00Z",
    expiresAt: "2025-08-16T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-036",
    title: "Urgent: School Closure Due to Heavy Rain",
    message:
      "Due to heavy rainfall and waterlogging in the area, the school will remain closed today (20th July 2025) as a precautionary measure. All exams scheduled for today have been postponed. New dates will be announced shortly. Students and staff are advised to stay safe.",
    category: NOTICE_CATEGORIES.EMERGENCY,
    priority: NOTICE_PRIORITIES.CRITICAL,
    sourceModule: "administration",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.ALL,
    },
    deliveryChannels: [
      DELIVERY_CHANNELS.PORTAL,
      DELIVERY_CHANNELS.SMS,
      DELIVERY_CHANNELS.WHATSAPP,
      DELIVERY_CHANNELS.PUSH,
    ],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      emergencyType: "weather",
      reason: "Heavy rainfall and waterlogging",
      closureDate: "2025-07-20T00:00:00Z",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-20T06:00:00Z",
    publishedAt: "2025-07-20T06:00:00Z",
    expiresAt: "2025-07-21T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-037",
    title: "Class XI-A Results Declared",
    message:
      "Results for the unit tests conducted in June 2025 for Class XI-A have been declared. Students can view their results in the portal. Parents are requested to review the performance and contact class teachers for any clarifications.",
    category: NOTICE_CATEGORIES.RESULTS,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "examinations",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-11a"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      examSessionId: "unit-test-june-2025",
      classId: "class-11a",
      resultUrl: "/results/class-11a-june-2025",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-15T12:00:00Z",
    publishedAt: "2025-07-15T12:00:00Z",
    expiresAt: "2025-08-15T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-038",
    title: "Timetable Revision - Class X",
    message:
      "The timetable for Class X has been revised effective from 22nd July 2025. Mathematics periods have been shifted to morning sessions. Updated timetable is available in the portal. Students and teachers are requested to note the changes.",
    category: NOTICE_CATEGORIES.TIMETABLE,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "academics",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.CLASS,
      classIds: ["class-10a", "class-10b", "class-10c", "class-10d"],
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      effectiveFrom: "2025-07-22T00:00:00Z",
      changes: ["Mathematics periods shifted to morning"],
      timetableUrl: "/timetables/class-10-revised",
    },
    createdBy: "admin-001",
    createdAt: "2025-07-16T10:00:00Z",
    publishedAt: "2025-07-16T10:00:00Z",
    expiresAt: "2025-08-01T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-039",
    title: "Disciplinary Policy Update",
    message:
      "The school disciplinary policy has been updated with new guidelines regarding mobile phone usage and dress code. All students and parents are requested to review the updated policy available in the student handbook. Implementation begins from 1st August 2025.",
    category: NOTICE_CATEGORIES.DISCIPLINE,
    priority: NOTICE_PRIORITIES.IMPORTANT,
    sourceModule: "administration",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.ALL,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL, DELIVERY_CHANNELS.EMAIL],
    requiresAction: true,
    actionType: ACTION_TYPES.ACKNOWLEDGE,
    metadata: {
      policyUrl: "/documents/disciplinary-policy-2025.pdf",
      effectiveFrom: "2025-08-01T00:00:00Z",
      changes: ["Mobile phone usage guidelines", "Dress code updates"],
    },
    createdBy: "admin-001",
    createdAt: "2025-07-17T11:00:00Z",
    publishedAt: "2025-07-17T11:00:00Z",
    expiresAt: "2025-08-15T00:00:00Z",
    readReceipts: [],
  },
  {
    id: "notice-030",
    title: "System Maintenance Scheduled",
    message:
      "The EduDash portal will undergo scheduled maintenance on 25th July 2025 from 2:00 AM to 4:00 AM IST. The portal will be inaccessible during this period. Users are requested to plan their activities accordingly.",
    category: NOTICE_CATEGORIES.SYSTEM,
    priority: NOTICE_PRIORITIES.INFO,
    sourceModule: "system",
    status: NOTICE_STATUS.PUBLISHED,
    targetAudience: {
      type: AUDIENCE_TYPES.ALL,
    },
    deliveryChannels: [DELIVERY_CHANNELS.PORTAL],
    requiresAction: false,
    actionType: ACTION_TYPES.NONE,
    metadata: {
      maintenanceStart: "2025-07-25T02:00:00Z",
      maintenanceEnd: "2025-07-25T04:00:00Z",
      impact: "Portal will be inaccessible",
    },
    createdBy: "system",
    createdAt: "2025-07-18T15:00:00Z",
    publishedAt: "2025-07-18T15:00:00Z",
    expiresAt: "2025-07-26T00:00:00Z",
    readReceipts: [],
  },
];

export default noticeSeedData;
